flotte/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from pages import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    # path(
    #     '',
    #    views.base,
    #     name='base'
    # ),
]

if settings.DEBUG :
    urlpatterns +=static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path



from pages import views


app_name = 'pages'
urlpatterns = [
    path("", views.home, name="home") ,
    path("connexion", views.connexion, name="connexion") ,
    path("deconnexion", views.deconnexion, name="deconnexion") ,
    path("inscription", views.inscription, name="inscription") ,
    path("forget_password", views.forget_password, name="forget_password") ,
    path("update_password", views.new_password, name="update_password") ,
    path("parametre", views.parametre, name="parametre") ,
    
    path("activate_account/<uidb64>/<token>/", views.activate_account, name="activate_account") ,
    path("reinitialiser_mdp/<uidb64>/<token>/", views.reinitialiser_mdp, name="reinitialiser_mdp") ,
    path("user_spec/<int:user_id>/", views.user_spec, name="user_spec") ,
    path("view_user", views.view_user, name="view_user") 
]

pages/templates/connexion.html
{% extends 'base.html' %}

{% block title %}
      Page|Connexion
{% endblock title %}
    

{% block css %}
    <style>
        .gradient-form{
            height: 50% !important;
        }
        .gradient-custom-2 {
            /* fallback for old browsers */
            background: #04BBFF;
            
            /* Chrome 10-25, Safari 5.1-6 */
            background: -webkit-linear-gradient(to right, #04BBFF, #04BBFF, #04BBFF, #04BBFF);
            
            /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
            background: linear-gradient(to right, #04BBFF, #04BBFF, #04BBFF, #04BBFF);
            }
            
            @media screen  (min-width: 768px) {
            .gradient-form {
            height: 100vh !important;
            }
            }
            @media screen (min-width: 769px) {
            .gradient-custom-2 {
            border-top-right-radius: .3rem;
            border-bottom-right-radius: .3rem;
            }
            }
    </style>
{% endblock css %}
    
{% block content %}
{% load static %}
<section class="gradient-form" >
    <div class="container py-1 ">
      <div class="row d-flex justify-content-center align-items-center ">
        <div class="col-xl-10">
          <div class="card rounded-3 text-black">
              
            {% if messages %}
                
                {% for message in messages %}
                <div class="alert alert-{% if message.tags == 'error' %}warning{% else %}success{% endif %} alert-dismissible fade show d-flex" role="alert">
                  
                  {% if message.tags == 'error'  %}
                  <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Warning:">
                    <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
                      <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                    </symbol>
                  <use xlink:href="#exclamation-triangle-fill"/></svg>
                  {% else %}
                  <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/>
                    <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
                      <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
                    </symbol>
                  </svg>
                  {% endif %}
                    
                 
                  <div>
                    <strong>Informations</strong> {{message}}.
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                  </div>
                
                </div>
                {% endfor %}
                  
            {% endif %}
            <div class="row g-0">
              <div class="col-lg-6">
                <div class="card-body px-md-5 mx-md-4">
  
                  <div class="text-center">
                    <img src="{% static 'images/logo/OIP (26).jpeg' %} " class="img-fluid "
                      style="width: 100px;" alt="logo">
                    <h4 class="mt-1 mb-2 pb-1">Agence APMF</h4>
                  </div>
  
                  <form method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                    <p>Please login to your account</p>
  
                    <div  class="form-outline mb-2 mx-1">
                      <input type="text" id="email" name="username" class="form-control rounded-pill  " required
                        placeholder="" />
                      <label class="form-label" for="email">Username</label>
                    </div>
  
                    <div class="form-outline mb-2 mx-1">
                      <input type="password" id="password" name="password" class="form-control  rounded-pill "  required />
                      <label class="form-label" for="password">Password</label>
                    </div>
  
                    <div class="text-center pt-1 mb-2 pb-1 d-flex flex-column">
                      <input value="Log in" class="btn btn-primary rounded-pill btn-block fa-lg  mb-3" type="submit">
                      <a class="text-muted" href="{% url 'pages:forget_password' %}">Forgot password?</a>
                    </div>
  
                    <div class="d-flex align-items-center justify-content-center pb-4">
                      <p class="mb-0 me-2">Don't have an account?</p>
                      <a  type="button" href="{% url 'pages:inscription' %}" class="btn btn-outline-primary rounded-pill">Create new</a>
                    </div>
  
                  </form>
  
                </div>
              </div>
              <div class="col-lg-6 d-none d-sm-flex align-items-center  bg-primary">
                <div class="text-white px-3 py-4 p-md-5 mx-md-4">
                  <h4 class="mb-4">Agence Portuaire Maritime Fluvial</h4>
                  <h6 class="large mb-0">Vers un Secteur Maritime et Fluvial Moderne,Pilier du Developpement Economique de Madagascar.</h6>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}
    

pages/templates/details.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <title>Cyborg - Awesome HTML5 Template</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="assets/css/fontawesome.css">
    <link rel="stylesheet" href="assets/css/templatemo-cyborg-gaming.css">
    <link rel="stylesheet" href="assets/css/owl.css">
    <link rel="stylesheet" href="assets/css/animate.css">
    <link rel="stylesheet"href="https://unpkg.com/swiper@7/swiper-bundle.min.css"/>
<!--

TemplateMo 579 Cyborg Gaming

https://templatemo.com/tm-579-cyborg-gaming

-->
  </head>

<body>

  <!-- ***** Preloader Start ***** -->
  <div id="js-preloader" class="js-preloader">
    <div class="preloader-inner">
      <span class="dot"></span>
      <div class="dots">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
  </div>
  <!-- ***** Preloader End ***** -->

  <!-- ***** Header Area Start ***** -->
  <header class="header-area header-sticky">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="main-nav">
                    <!-- ***** Logo Start ***** -->
                    <a href="index.html" class="logo">
                        <img src="assets/images/logo.png" alt="">
                    </a>
                    <!-- ***** Logo End ***** -->
                    <!-- ***** Search End ***** -->
                    <div class="search-input">
                      <form id="search" action="#">
                        <input type="text" placeholder="Type Something" id='searchText' name="searchKeyword" onkeypress="handle" />
                        <i class="fa fa-search"></i>
                      </form>
                    </div>
                    <!-- ***** Search End ***** -->
                    <!-- ***** Menu Start ***** -->
                    <ul class="nav">
                        <li><a href="index.html">Home</a></li>
                        <li><a href="browse.html">Browse</a></li>
                        <li><a href="details.html" class="active">Details</a></li>
                        <li><a href="streams.html">Streams</a></li>
                        <li><a href="profile.html">Profile <img src="assets/images/profile-header.jpg" alt=""></a></li>
                    </ul>   
                    <a class='menu-trigger'>
                        <span>Menu</span>
                    </a>
                    <!-- ***** Menu End ***** -->
                </nav>
            </div>
        </div>
    </div>
  </header>
  <!-- ***** Header Area End ***** -->

  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="page-content">

          <!-- ***** Featured Start ***** -->
          <div class="row">
            <div class="col-lg-12">
              <div class="feature-banner header-text">
                <div class="row">
                  <div class="col-lg-4">
                    <img src="assets/images/feature-left.jpg" alt="" style="border-radius: 23px;">
                  </div>
                  <div class="col-lg-8">
                    <div class="thumb">
                      <img src="assets/images/feature-right.jpg" alt="" style="border-radius: 23px;">
                      <a href="https://www.youtube.com/watch?v=r1b03uKWk_M" target="_blank"><i class="fa fa-play"></i></a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- ***** Featured End ***** -->

          <!-- ***** Details Start ***** -->
          <div class="game-details">
            <div class="row">
              <div class="col-lg-12">
                <h2>Fortnite Details</h2>
              </div>
              <div class="col-lg-12">
                <div class="content">
                  <div class="row">
                    <div class="col-lg-6">
                      <div class="left-info">
                        <div class="left">
                          <h4>Fortnite</h4>
                          <span>Sandbox</span>
                        </div>
                        <ul>
                          <li><i class="fa fa-star"></i> 4.8</li>
                          <li><i class="fa fa-download"></i> 2.3M</li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="right-info">
                        <ul>
                          <li><i class="fa fa-star"></i> 4.8</li>
                          <li><i class="fa fa-download"></i> 2.3M</li>
                          <li><i class="fa fa-server"></i> 36GB</li>
                          <li><i class="fa fa-gamepad"></i> Action</li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-lg-4">
                      <img src="assets/images/details-01.jpg" alt="" style="border-radius: 23px; margin-bottom: 30px;">
                    </div>
                    <div class="col-lg-4">
                      <img src="assets/images/details-02.jpg" alt="" style="border-radius: 23px; margin-bottom: 30px;">
                    </div>
                    <div class="col-lg-4">
                      <img src="assets/images/details-03.jpg" alt="" style="border-radius: 23px; margin-bottom: 30px;">
                    </div>
                    <div class="col-lg-12">
                      <p>Cyborg Gaming is free HTML CSS website template provided by TemplateMo. This is Bootstrap v5.2.0 layout. You can make a <a href="https://paypal.me/templatemo" target="_blank">small contribution via PayPal</a> to info [at] templatemo.com and thank you for supporting. If you want to get the PSD source files, please contact us. Lorem ipsum dolor sit consectetur es dispic dipiscingei elit, sed doers eiusmod lisum hored tempor.</p>
                    </div>
                    <div class="col-lg-12">
                      <div class="main-border-button">
                        <a href="#">Download Fortnite Now!</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- ***** Details End ***** -->

          <!-- ***** Other Start ***** -->
          <div class="other-games">
            <div class="row">
              <div class="col-lg-12">
                <div class="heading-section">
                  <h4><em>Other Related</em> Games</h4>
                </div>
              </div>
              <div class="col-lg-6">
                <div class="item">
                  <img src="assets/images/game-01.jpg" alt="" class="templatemo-item">
                  <h4>Dota 2</h4><span>Sandbox</span>
                  <ul>
                    <li><i class="fa fa-star"></i> 4.8</li>
                    <li><i class="fa fa-download"></i> 2.3M</li>
                  </ul>
                </div>
              </div>
              <div class="col-lg-6">
                <div class="item">
                  <img src="assets/images/game-02.jpg" alt="" class="templatemo-item">
                  <h4>Dota 2</h4><span>Sandbox</span>
                  <ul>
                    <li><i class="fa fa-star"></i> 4.8</li>
                    <li><i class="fa fa-download"></i> 2.3M</li>
                  </ul>
                </div>
              </div>
              <div class="col-lg-6">
                <div class="item">
                  <img src="assets/images/game-03.jpg" alt="" class="templatemo-item">
                  <h4>Dota 2</h4><span>Sandbox</span>
                  <ul>
                    <li><i class="fa fa-star"></i> 4.8</li>
                    <li><i class="fa fa-download"></i> 2.3M</li>
                  </ul>
                </div>
              </div>
              <div class="col-lg-6">
                <div class="item">
                  <img src="assets/images/game-02.jpg" alt="" class="templatemo-item">
                  <h4>Dota 2</h4><span>Sandbox</span>
                  <ul>
                    <li><i class="fa fa-star"></i> 4.8</li>
                    <li><i class="fa fa-download"></i> 2.3M</li>
                  </ul>
                </div>
              </div>
              <div class="col-lg-6">
                <div class="item">
                  <img src="assets/images/game-03.jpg" alt="" class="templatemo-item">
                  <h4>Dota 2</h4><span>Sandbox</span>
                  <ul>
                    <li><i class="fa fa-star"></i> 4.8</li>
                    <li><i class="fa fa-download"></i> 2.3M</li>
                  </ul>
                </div>
              </div>
              <div class="col-lg-6">
                <div class="item">
                  <img src="assets/images/game-01.jpg" alt="" class="templatemo-item">
                  <h4>Dota 2</h4><span>Sandbox</span>
                  <ul>
                    <li><i class="fa fa-star"></i> 4.8</li>
                    <li><i class="fa fa-download"></i> 2.3M</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <!-- ***** Other End ***** -->

        </div>
      </div>
    </div>
  </div>
  
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <p>Copyright © 2036 <a href="#">Cyborg Gaming</a> Company. All rights reserved. 
          
          <br>Design: <a href="https://templatemo.com" target="_blank" title="free CSS templates">TemplateMo</a></p>
        </div>
      </div>
    </div>
  </footer>


  <!-- Scripts -->
  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.min.js"></script>

  <script src="assets/js/isotope.min.js"></script>
  <script src="assets/js/owl-carousel.js"></script>
  <script src="assets/js/tabs.js"></script>
  <script src="assets/js/popup.js"></script>
  <script src="assets/js/custom.js"></script>


  </body>

</html>

pages/templates/forget_password.html
{% extends 'base.html' %}

{% block title %}
      Page|Mot de passe oublié
{% endblock title %}
    

{% block css %}
    <style>
       
       
    </style>
{% endblock css %}
    
{% block content %}
<div class="row " style="height: 70vh;">
    <div class="col-12 d-flex justify-content-center align-items-center">
        <div class="card text-center" style="width: 400px;">
            {% if messages %}
                
                {% for message in messages %}
                <div class="alert alert-{% if message.tags == 'error' %}warning{% else %}success{% endif %} alert-dismissible fade show d-flex" role="alert">
                  
                  {% if message.tags == 'error'  %}
                  <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Warning:">
                    <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
                      <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                    </symbol>
                  <use xlink:href="#exclamation-triangle-fill"/></svg>
                  {% else %}
                  <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/>
                    <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
                      <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
                    </symbol>
                  </svg>
                  {% endif %}
                    
                 
                  <div>
                    <strong>Informations</strong> {{message}}.
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                  </div>
                
                </div>
                {% endfor %}
                  
            {% endif %}
            <div class="card-header h5 text-white bg-primary">Password Reset</div>
            <div class="card-body px-5">
                <p class="card-text py-2">
                    Enter your email address and we'll send you an email with instructions to reset your password.
                </p>
                <form action="" method="post">
                    {% csrf_token %}
                    <div data-mdb-input-init class="form-outline">
                        <input type="email" name="email" id="typeEmail" required class="form-control my-3 rounded-pill" />
                      
                    </div>
                    <input type="submit" value="Reset password" data-mdb-ripple-init class="btn btn-primary w-100 rounded-pill">
                    
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
    

pages/templates/home.html
{% extends 'base.html' %}

{% block title %}
      Page|Home
{% endblock title %}
    

{% block css %}
    <style>
    
    </style>
{% endblock css %}
    
{% block content %}
{% load static %}
<section class="gradient-form" >
  <div class="row ">
     
     {% for user in users %}
     <div class="col-12 mx-0  col-sm-6 col-md-4 col-lg-3 col-xl-2 my-2">

        <div class="card text-center h-100" >
                     <div class="card-header bg-black text-white  text-uppercase">{{user.username }}</div>
           
            <div class="card-body flex-column d-flex justify-content-center">
             <div class="image " >
              {% if user.imageuser  %}
              <img width="100" height="100" class="card-img-top object-fit-contain  Card img-fluid" src="{% static 'images/'%}{{user.imageuser}}"   alt=" image">
              {% else %}
                <img src="{% static 'images/profil_user/logo_profil.jpeg' %} " class="object-fit-contain Card img-fluid image"
               alt="logo">
             {% endif %}
             </div>
              <h4 class="card-title">{{user.first_name|truncatechars:10}}</h4>
              <p class="card-text">{{user.last_name|truncatechars:10}}</p>
             
            </div>
            <div class="card-footer d-flex  justify-content-center">
             
                <a href="{% url 'pages:user_spec' user.id %}"   data-id = {{user.id}} class=" w-100 btn btn-outline-primary btn-md rounded-pill view_user">Voir Profil</a>
              
            </div>
          </div>          
    </div>
     {% endfor %}
        
  </div>
  </section>
{% endblock content %}
    

pages/templates/inscription.html
{% extends 'base.html' %}

{% block title %}
      Page|Inscription
{% endblock title %}
    

{% block css %}
<style>
  .gradient-form{
      height: 50% !important;
  }
  .gradient-custom-2 {
      /* fallback for old browsers */
      background: #04BBFF;
      
      /* Chrome 10-25, Safari 5.1-6 */
      background: -webkit-linear-gradient(to right, #04BBFF, #04BBFF, #04BBFF, #04BBFF);
      
      /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
      background: linear-gradient(to right, #04BBFF, #04BBFF, #04BBFF, #04BBFF);
      }
      
      @media screen  (min-width: 768px) {
      .gradient-form {
      height: 100vh !important;
      }
      }
      @media screen (min-width: 769px) {
      .gradient-custom-2 {
      border-top-right-radius: .3rem;
      border-bottom-right-radius: .3rem;
      }
      }
</style>
{% endblock css %}
    
{% block content %}
{% load static %}
<section class="gradient-form" >
    <div class="container py-1 ">
      <div class="row d-flex justify-content-center align-items-center ">
        <div class="col-xl-10">
          <div class="card rounded-3 text-black">
            
            
            {% if messages %}
                
                {% for message in messages %}
                <div class="alert alert-{% if message.tags == 'error' %}warning{% else %}success{% endif %} alert-dismissible fade show d-flex" role="alert">
                  
                  {% if message.tags == 'error'  %}
                  <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Warning:">
                    <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
                      <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                    </symbol>
                  <use xlink:href="#exclamation-triangle-fill"/></svg>
                  {% else %}
                  <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/>
                    <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
                      <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
                    </symbol>
                  </svg>
                  {% endif %}
                    
                 
                  <div>
                    <strong>Informations</strong> {{message}}.
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                  </div>
                
                </div>
                {% endfor %}
                  
            {% endif %}
              
            
            <div class="row g-0">
              <div class="col-lg-6">
                <div class="card-body px-md-5 mx-md-4">
                  
                  <div class="text-center">
                    <img src="{% static 'images/logo/OIP (26).jpeg' %} " class="img-fluid "
                      style="width: 100px;" alt="logo">
                    <h4 class="mt-1 mb-2 pb-1 text-uppercase">Agence APMF</h4>
                  </div>
  
                  <form method="POST">
                    {% csrf_token %}
                    <p>Please create your account</p>
  
                      <div class=" d-inline d-sm-flex">
                        <div class="form-outline mb-1 mx-1">
                          <input type="text" id="username" class="form-control rounded-pill  " required name= "username"
                            placeholder=" " />
                          <label class="form-label" for="username">Username</label>
                        </div>
      
                        <div  class="form-outline mb-1">
                          <input type="email" id="email" class="form-control  rounded-pill " required  name= "email" />
                          <label class="form-label" for="email">Email adress</label>
                        </div>
                      </div>
                     <div class=" d-inline d-sm-flex justify-content-between ">
                      <div  class="form-outline mb-1 mx-1">
                        <input type="text" id="first_name" class="form-control  rounded-pill " required name= "first_name" />
                        <label class="form-label" for="first_name">First name</label>
                      </div>
                      <div  class="form-outline mb-1">
                        <input type="text" id="last_name" class="form-control  rounded-pill " required name= "last_name" />
                        <label class="form-label" for="last_name">Last name</label>
                      </div>
                     </div>
                    <div  class="form-outline mb-1 mx-1">
                      <input type="password" id="password" class="form-control  rounded-pill " required name= "password" />
                      <label class="form-label" for="password">Password</label>
                    </div>
                    <div  class="form-outline mb-1 mx-1">
                      <input type="password" id="password_repeat" class="form-control  rounded-pill " required name= "password_repeat" />
                      <label class="form-label" for="password_repeat">Repeat Password</label>
                    </div>
  
                    <div class="text-center mx-1 pt-1 mb-2 pb-1 d-flex flex-column">
                      <input  class="btn btn-danger rounded-pill btn-block fa-lg  mb-3" value="Register" type="submit">
                      
                     
                    </div>
  
                    <div class="d-flex align-items-center justify-content-center pb-4">
                      <p class="mb-0 me-2">Have already an account?</p>
                      <a  href="{% url 'pages:connexion' %}"  class="btn btn-outline-danger rounded-pill">Login here</a>
                    </div>
  
                  </form>
  
                </div>
              </div>
              <div class="col-lg-6 d-none d-sm-flex align-items-center  bg-primary">
                <div class="text-white px-3 py-4 mb-5 p-md-5 mx-md-4">
                  <h4 class="mb-4">Agence Portuaire Maritime Fluvial</h4>
                  <h6 class="large mb-0">Vers un Secteur Maritime et Fluvial Moderne,Pilier du Developpement Economique de Madagascar.</h6>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}
    
    

pages/templates/mail_reinitialisation_mdp.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reinitialisation de mot de passe</title>
    <style>
        /* Styles Bootstrap simplifiés pour les emails */
        body {
            font-family: Arial, sans-serif;
            background-color: #f9f9f9;
            margin: 0;
            padding: 0;
        }
        .container {
            width: 100%;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #dddddd;
            background-color: #ffffff;
        }
        .btn {
            display: inline-block;
            font-weight: 400;
            text-align: center;
            white-space: nowrap;
            vertical-align: middle;
            user-select: none;
            border: 1px solid transparent;
            padding: 0.375rem 0.75rem;
            font-size: 1rem;
            line-height: 1.5;
            border-radius: 0.25rem;
            color: #ffffff;
            background-color: #007bff;
            text-decoration: none;
        }
        .btn:hover {
            background-color: #0056b3;
        }
        .text-center {
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="text-center">
            <h1>Reinitialisation de mot de passe</h1>
        </div>
        <p>Bonjour {{ user }},</p>
        <p>Veuillez cliquer sur le bouton ci-dessous pour reinitialiser votre mot de passe :</p>
        <div class="text-center">
            <a href="http://{{domain}}{% url 'pages:reinitialiser_mdp' uidb64=uid token=token %}" class="btn">Reinitialiser mon mot de passe</a>
        </div>
        <p>Si vous n'avez pas reinitialiserée votre mot de passe sur notre site, veuillez ignorer cet email.</p>
        <div class="footer">
            <div>
                <img src="{% static 'images/email/image001.png' %}" alt="" srcset="">
            </div>
            <p>&copy; 2024 AGENCE APMF . Tous droits réservés.</p>
        </div>
    </div>
</body>
</html>